<script>
        var HOST_URL = "<?php echo DIR; ?>";
        var USERNAME = "<?php echo $username; ?>";
        var EV_ID = "<?php echo $id; ?>";
        var TRAN_STOP = "<?= $ml->tr('STOP') ?>";
        var TRAN_PLAY = "<?= $ml->tr('PLAY') ?>";
        var TRAN_SEGUE = "<?= $ml->tr('SEGUE') ?>";
        var TRAN_TRACK = "<?= $ml->tr('TRACK') ?>";
        var TRAN_MARKER = "<?= $ml->tr('MARKER') ?>";
        var TRAN_MOVEUP = "<?= $ml->tr('MOVEUP') ?>";
        var TRAN_MOVEDOWN = "<?= $ml->tr('MOVEDOWN') ?>";
        var TRAN_VTRACK = "<?= $ml->tr('BRACKVOICETRACK') ?>";
        var TRAN_LNOTE = "<?= $ml->tr('BRACKLOGNOTE') ?>";
        var TRAN_PLAYTRANS = "<?= $ml->tr('PLAYTRANS') ?>";
        var TRAN_SEGUETRANS = "<?= $ml->tr('SEGUETRANS') ?>";
        var TRAN_AUTO = "<?= $ml->tr('BRACKAUTO') ?>";
        var TRAN_EDIT = "<?= $ml->tr('EDIT') ?>";
        var TRAN_REMOVE = "<?= $ml->tr('REMOVE') ?>";
        var TRAN_REMOVEIMP = "<?= $ml->tr('REMEVENTLINE') ?>";
        var TRAN_CLOSETHEWINDOW = "<?= $ml->tr('CLOSETHEWINDOW') ?>";
        var TRAN_VTHEAD = "<?= $ml->tr('VOICETRACKMARKER') ?>";
        var TRAN_VTNOTE = "<?= $ml->tr('VOICETRACKNOTE') ?>";
        var TRAN_MKHEAD = "<?= $ml->tr('LOGNOTE') ?>";
        var TRAN_YES = "<?= $ml->tr('YES') ?>";
        var TRAN_NO = "<?= $ml->tr('NO') ?>";
        var TRAN_OK = "<?= $ml->tr('OK') ?>";
        var TRAN_BUG = "<?= $ml->tr('BUG') ?>";
        var TRAN_NOTBEEMPTY = "<?= $ml->tr('NOTBEEMPTY') ?>";
        var TRAN_NOTPOSSIBLEMARKER = "<?= $ml->tr('NOTPOSSIBLEMARKER') ?>";
        var TRAN_NOTCORRECTTIMEFORM = "<?= $ml->tr('NOTCORRECTTIMEFORM') ?>";
        var TRAN_ONLYDIGITS = "<?= $ml->tr('ONLYDIGITS') ?>";
        var TRAN_EVENTHASSAVED = "<?= $ml->tr('EVENTHASSAVED') ?>";
        var TRAN_NOTPOSSIBLESAVETHEEVENT = "<?= $ml->tr('NOTPOSSIBLESAVETHEEVENT') ?>";
        var TRAN_TABLEFIRST = "<?= $ml->tr('TAFIRST') ?>";
        var TRAN_TABLELAST = "<?= $ml->tr('TALAST') ?>";
        var TRAN_TABLENEXT = "<?= $ml->tr('TANEXT') ?>";
        var TRAN_TABLEPREV = "<?= $ml->tr('TAPREVIUS') ?>";
        var TRAN_TABLESHOW = "<?= $ml->tr('TASHOW') ?>";
        var TRAN_TABLESELECTED = "<?= $ml->tr('SELECTED') ?>";
        var TRAN_TABLENODATA = "<?= $ml->tr('TABLENODATA') ?>";
        var TRAN_TABLESHOWS = "<?= $ml->tr('SHOWS') ?>";
        var TRAN_TABLETO = "<?= $ml->tr('TO') ?>";
        var TRAN_TABLETOTAL = "<?= $ml->tr('OFTOTAL') ?>";
        var TRAN_TABLEROWS = "<?= $ml->tr('ROWS') ?>";
        var TRAN_TABLEFILTERED = "<?= $ml->tr('FILTEREDFROM') ?>";
        var TRAN_TABLELOADING = "<?= $ml->tr('LOADING') ?>";
        var TRAN_TABLEWORKING = "<?= $ml->tr('WORKING') ?>";
        var TRAN_TABLESEARCH = "<?= $ml->tr('SEARCH') ?>";
        var TRAN_TABLENSORTRISE = "<?= $ml->tr('ENABLERISING') ?>";
        var TRAN_TABLENSORTFALL = "<?= $ml->tr('ENABLEFALLING') ?>";
        var TRAN_TABLENORESULTS = "<?= $ml->tr('NORESULTS') ?>";
        var TRAN_SELECTNORESULTS = "<?= $ml->tr('NORESULTSFOUNDSELECT') ?>";
        var TRAN_SELECTNOOPTIONS = "<?= $ml->tr('NOOPTIONSSELECT') ?>";
        var TRAN_SELECTPRESSSELECT = "<?= $ml->tr('PRESSSELECTSELECT') ?>";
    </script>