<script>
    var HOST_URL = "<?php echo DIR; ?>";
    var TRAN_EDIT = "<?= $ml->tr('EDIT') ?>";
    var TRAN_REMOVE = "<?= $ml->tr('REMOVE') ?>";
    var TRAN_SEARCHSWITCH = "<?= $ml->tr('SEARCHFORSWITCH') ?>";
    var TRAN_SEARCHOUTPUT = "<?= $ml->tr('SEARCHOUTPUT') ?>";
    var TRAN_SEARCHINPUT = "<?= $ml->tr('SEARCHINPUT') ?>";
    var TRAN_SEARCHPORT = "<?= $ml->tr('SEARCHPORT') ?>";
    var TRAN_OFF = "<?= $ml->tr('OFF') ?>";
    var USERNAME = "<?php echo $username; ?>";  
    var TRAN_CLOSETHEWINDOW = "<?= $ml->tr('CLOSETHEWINDOW') ?>";
    var TRAN_YES = "<?= $ml->tr('YES') ?>";
    var TRAN_NO = "<?= $ml->tr('NO') ?>";
    var TRAN_OK = "<?= $ml->tr('OK') ?>";
    var TRAN_BUG = "<?= $ml->tr('BUG') ?>";
    var TRAN_NOTBEEMPTY = "<?= $ml->tr('NOTBEEMPTY') ?>";
    var TRAN_TABLEFIRST = "<?= $ml->tr('TAFIRST') ?>";
    var TRAN_TABLELAST = "<?= $ml->tr('TALAST') ?>";
    var TRAN_TABLENEXT = "<?= $ml->tr('TANEXT') ?>";
    var TRAN_TABLEPREV = "<?= $ml->tr('TAPREVIUS') ?>";
    var TRAN_TABLESHOW = "<?= $ml->tr('TASHOW') ?>";
    var TRAN_TABLESELECTED = "<?= $ml->tr('SELECTED') ?>";
    var TRAN_TABLENODATA = "<?= $ml->tr('TABLENODATA') ?>";
    var TRAN_TABLESHOWS = "<?= $ml->tr('SHOWS') ?>";
    var TRAN_TABLETO = "<?= $ml->tr('TO') ?>";
    var TRAN_TABLETOTAL = "<?= $ml->tr('OFTOTAL') ?>";
    var TRAN_TABLEROWS = "<?= $ml->tr('ROWS') ?>";
    var TRAN_TABLEFILTERED = "<?= $ml->tr('FILTEREDFROM') ?>";
    var TRAN_TABLELOADING = "<?= $ml->tr('LOADING') ?>";
    var TRAN_TABLEWORKING = "<?= $ml->tr('WORKING') ?>";
    var TRAN_TABLESEARCH = "<?= $ml->tr('SEARCH') ?>";
    var TRAN_TABLENSORTRISE = "<?= $ml->tr('ENABLERISING') ?>";
    var TRAN_TABLENSORTFALL = "<?= $ml->tr('ENABLEFALLING') ?>";
    var TRAN_TABLENORESULTS = "<?= $ml->tr('NORESULTS') ?>";
</script>